# knowledge graph notes for mathematics
import KnowledgeGraphNote.Concept

math_notes = [
    Concept("radon measure",
            "https://mathworld.wolfram.com/RadonMeasure.html",
            ["borel measure", "compact set"],
            "a radon measure is a Borel measure that is finite on compact sets."
            ),

    Concept("Borel measure",
            "https://mathworld.wolfram.com/BorelMeasure.html",
            ["borel sigma-algebra", "topological space",  "measure", "measurable"],
            "if f is the borel sigma-algebra on some topological space, then a measure m:f->r is said to be a borel measure (or borel probability measure). for a borel measure, all continuous functions are measurable."
            ),

    Concept("borel sigma-algebra",
            "https://mathworld.wolfram.com/BorelSigma-Algebra.html",
            ["sigma-algebra", "topological space", "set", "open set", "closed set"],
            "a sigma-algebra which is related to the topology of a set. the borel sigma-algebra is defined to be the sigma-algebra generated by the open sets (or equivalently, by the closed sets)."
            ),

    Concept("topological space",
            "https://mathworld.wolfram.com/TopologicalSpace.html",
            ["empty set", "set", "open set"],
            """A topological space, also called an abstract topological space, is a set X together with a collection of open subsets T that satisfies the four conditions:

1. The empty set emptyset is in T.

2. X is in T.

3. The intersection of a finite number of sets in T is also in T.

4. The union of an arbitrary number of sets in T is also in T.

Alternatively, T may be defined to be the closed sets rather than the open sets, in which case conditions 3 and 4 become:

3. The intersection of an arbitrary number of sets in T is also in T.

4. The union of a finite number of sets in T is also in T.

These axioms are designed so that the traditional definitions of open and closed intervals of the real line continue to be true. For example, the restriction in (3) can be seen to be necessary by considering  intersection _(n=1)^infty(-1/n,1/n)={0}, where an infinite intersection of open intervals is a closed set.

In the chapter "Point Sets in General Spaces" Hausdorff (1914) defined his concept of a topological space based on the four Hausdorff axioms (which in modern times are not considered necessary in the definition of a topological space)."""
            ),

    Concept("borel sigma-algebra",
            "https://mathworld.wolfram.com/BorelSigma-Algebra.html",
            ["sigma-algebra", "topological space", "set", "open set", "closed set"],
            "a sigma-algebra which is related to the topology of a set. the borel sigma-algebra is defined to be the sigma-algebra generated by the open sets (or equivalently, by the closed sets)."
            ),

    Concept("sigma-algebra",
            "https://mathworld.wolfram.com/Sigma-Algebra.html",
            ["set", "power set"],
            """
    Let X be a set. Then a sigma-algebra F is a nonempty collection of subsets of X such that the following hold:

1. X is in F.

2. If A is in F, then so is the complement of A.

3. If A_n is a sequence of elements of F, then the union of the A_ns is in F.

If S is any collection of subsets of X, then we can always find a sigma-algebra containing S, namely the power set of X. By taking the intersection of all sigma-algebras containing S, we obtain the smallest such sigma-algebra. We call the smallest sigma-algebra containing S the sigma-algebra generated by S.
"""
            ),
    Concept("probability simplex",
            "https://web.stanford.edu/~boyd/cvxbook/bv_cvxbook.pdf",
            ["simplex"],
            """
The probability simplex is the (n − 1) dimensional simplex determined by the unit vectors e1, . . . , en ∈ Rn. It is the set of vectors that satisfy
x >= 0, 1^T x <= 1.
Vectors in the probability simplex correspond to probability distributions on a set with n elements, with xi interpreted as the probability of the ith element.
    """
            ),
    Concept("simplex",
            "https://web.stanford.edu/~boyd/cvxbook/bv_cvxbook.pdf",
            ["affinely independent", "linearly independent"],
            """
Simplexes are another important family of polyhedra. Suppose the k + 1 points v0, . . . , vk ∈ Rn are affinely independent, which means v1 − v0, . . . , vk − v0 are linearly independent. The simplex determined by them is given by
C = conv{v0, . . . , vk} = {θ0v0 + · · · + θkvk | θ >= 0, 1^Tθ = 1}
where 1 denotes the vector with all entries one. The affine dimension of this simplex is k, so it is sometimes referred to as a k-dimensional simplex in Rn
                    """
            ),
    Concept("linearly independent",
            "https://mathworld.wolfram.com/LinearlyDependentVectors.html",
            [],
            """
n vectors X_1, X_2, ..., X_n are linearly dependent iff there exist scalars c_1, c_2, ..., c_n, not all zero, such that
 sum_(i=1)^nc_iX_i=0.
If no such scalars exist, then the vectors are said to be linearly independent. 
                    """
            ),
    Concept("set",
            "https://mathworld.wolfram.com/Set.html",
            [],
            "A set is a finite or infinite collection of objects in which order has no significance, and multiplicity is generally also ignored (unlike a list or multiset). Members of a set are often referred to as elements and the notation a in A is used to denote that a is an element of a set A. The study of sets and their properties is the object of set theory."
            ),
    Concept("open set",
            "https://mathworld.wolfram.com/OpenSet.html",
            ["metric space", "neighborhood", ],
            """
Let S be a subset of a metric space. Then the set S is open if every point in S has a neighborhood lying in the set. An open set of radius r and center x_0 is the set of all points x such that |x-x_0|<r, and is denoted D_r(x_0). In one-space, the open set is an open interval. In two-space, the open set is a disk. In three-space, the open set is a ball.
"""
            ),
    Concept("Metric Space",
            "https://mathworld.wolfram.com/MetricSpace.html",
            ["metric"],
            """
A metric space is a set S with a global distance function (the metric g) that, for every two points x,y in S, gives the distance between them as a nonnegative real number g(x,y). A metric space must also satisfy

1. g(x,y)=0 iff x=y,

2. g(x,y)=g(y,x),

3. The triangle inequality g(x,y)+g(y,z)>=g(x,z).
"""
            ),
    Concept("Metric",
            "https://mathworld.wolfram.com/Metric.html",
            [],
            """
A nonnegative function g(x,y) describing the "distance" between neighboring points for a given set. A metric satisfies the triangle inequality

 g(x,y)+g(y,z)>=g(x,z) 	(1)
and is symmetric, so

 g(x,y)=g(y,x). 	(2)
A metric also satisfies

 g(x,x)=0, 	(3)
as well as the condition that g(x,y)=0 implies x=y. If this latter condition is dropped, then g(x,y) is called a pseudometric instead of a metric.
"""
            ),
    Concept("Tensor",
            "https://mathworld.wolfram.com/Tensor.html",
            [],
            """
An nth-rank tensor in m-dimensional space is a mathematical object that has n indices and m^n components and obeys certain transformation rules. Each index of a tensor ranges over the number of dimensions of space. However, the dimension of the space is largely irrelevant in most tensor equations (with the notable exception of the contracted Kronecker delta). Tensors are generalizations of scalars (that have no indices), vectors (that have exactly one index), and matrices (that have exactly two indices) to an arbitrary number of indices.

Tensors provide a natural and concise mathematical framework for formulating and solving problems in areas of physics such as elasticity, fluid mechanics, and general relativity.

The notation for a tensor is similar to that of a matrix (i.e., A=(a_(ij))), except that a tensor a_(ijk...), a^(ijk...), a_i^(jk)..., etc., may have an arbitrary number of indices. In addition, a tensor with rank r+s may be of mixed type (r,s), consisting of r so-called "contravariant" (upper) indices and s "covariant" (lower) indices. Note that the positions of the slots in which contravariant and covariant indices are placed are significant so, for example, a_(munu)^lambda is distinct from a_mu^(nulambda).
"""
            ),
    Concept("Closed set",
            "https://mathworld.wolfram.com/ClosedSet.html",
            ["set", "metric space", "set closure", "neighborhood", "Limit Point"],
            """
There are several equivalent definitions of a closed set. Let S be a subset of a metric space. A set S is closed if

1. The complement of S is an open set,

2. S is its own set closure,

3. Sequences/nets/filters in S that converge do so within S,

4. Every point outside S has a neighborhood disjoint from S.

The point-set topological definition of a closed set is a set which contains all of its limit points. Therefore, a closed set C is one for which, whatever point x is picked outside of C, x can always be isolated in some open set which doesn't touch C.
"""
            ),
    Concept("measurable",
            "https://mathworld.wolfram.com/MeasurableSet.html",
            ["sigma-algebra"],
            """
If F is a sigma-algebra and A is a subset of X, then A is called measurable if A is a member of F. X need not have, a priori, a topological structure. Even if it does, there may be no connection between the open sets in the topology and the given sigma-algebra.
"""
            )            
]

# the library will ignore case differences in names and dependency names.
duplicate_notes = [
    Concept("a", "empty link", [], "empty text"),
    Concept("b", "empty link", [], "empty text"),
    Concept("A", "empty link", [], "empty text"),
]


# circular definition: https://en.wikipedia.org/wiki/Circular_definition
# avoid them
cyclic_notes = [
    Concept("a", "empty link", ["B"], "empty text"),
    Concept("b", "empty link", ["c"], "empty text"),
    Concept("c", "empty link", ["a"], "empty text"),
]
