name = "KnowledgeGraphNote"
uuid = "31a8141b-b25f-4f91-ab3d-ca5dfa46aa1c"
authors = ["Song Wei <1983.song.wei@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
